apiVersion: apps/v1
kind: Deployment
metadata:
  name: awesomeapp
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: mistercamilo/awesomeapp:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          env:
            - name: MONGODB_URI
              value: mongodb://mongodbuser:mongodbpwd@mongo-service:27017/admin
#          livenessProbe:
#            httpGet:
#              path: /health
#              port: 8080
